name: HACS极速版安装器
version: "1.3.1"
slug: get
image: "ghcr.nju.edu.cn/hacs-china/{arch}-addon-get"
description: 最简单的HACS极速版安装方式
startup: once
boot: manual
url: "https://github.com/imkarl/addons/tree/main/get"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
schema:
  channel: list(current|development)?
map:
  - homeassistant_config:rw
